0xPolygon/static

minify.js
package-lock.json

Removed redundant line of code from `minify.js`

Removed redundant line of code

---

network/mainnet/v1/artifacts/pos/ChildERC721.json
network/mainnet/v1/artifacts/pos/ChildMintableERC721.json
network/mainnet/v1/artifacts/pos/DummyERC721.json
network/testnet/mumbai/artifacts/pos/ChildERC721.json
network/testnet/mumbai/artifacts/pos/ChildMintableERC721.json
network/testnet/mumbai/artifacts/pos/DummyERC721.json
package.json

Due to recent update performed in [pos-portal](https://github.com/maticnetwork/pos-portal/pull/70) contracts, interfaces has changed slightly. 
This PR pushes those updated ABI arrays in this repo.

Updated ABI array of default child ERC721, mintable child ERC721

---

.github/workflows/npm-release.yml

It'll be easier for us if NPM auto release it set up﻿.

Auto NPM Release

---

.github/workflows/npm-release.yml
package.json

Making `minify` command running implicit using prepublish hook.

Minify using `prepublish` hook

---

network/mainnet/v1/index.json
network/testnet/mumbai/index.json

Eth and goerli - true
matic and mumbai - false

Add supportsEIP1559 param

---

network/testnet/mumbai/index.json

added the address of the goerli multisig as "owner"

add multisig as "owner"

---

network/mainnet/v1/index.json

Burn contracts have been updated in the Agra hardfork.

update eip1559 new burn child contract

---

.github/workflows/staging_deployment.yml
Dockerfile
staging-taskdef.json

Staging environment deployment

Static staging deployment workflow

---

.github/workflows/staging_deployment.yml
staging-taskdef.json

Fix the secret env variable access.

Devops 2599 static staging app infra

---

.github/workflows/build_and_deploy.yml
.github/workflows/deployment.yml
README.md

Deployment workflow tested on local branch.

Deployment update for master static

---

.github/workflows/deployment.yml

Update deployment workflow.

---

Dockerfile
nginx.conf

Added nginx.conf to handle cors issue

Add nginx.conf file for handling cors

---

.github/workflows/deployment.yml
nginx.conf

Deploy with cors headers enabled

Devops 2599 cors issue update

---

index.html
nginx.conf

Healthcheck path updated and index.html added

landing page for static app with health check config

---

nginx.conf

Update allow methods

---

nginx.conf

Update location for health check

Update location for index

---

Dockerfile
nginx.conf

Update for nginx

---

nginx.conf

nginx.conf update for static app

---

.github/taskdef/prod-taskdef.yaml
.github/workflows/build_and_deploy.yml

App name update for static from static-prod to static

Static app name updated from static-prod to static

---

Dockerfile

making few changes to Dockerfile

---

.github/workflows/deployment_gcp.yml

GCP deployment update to publish docker image to artifact repository

GCP deployment update

---

.github/workflows/deployment_gcp.yml

Workflow update for releasing gcp docker image

Workflow update for releasing gcp docker image
